### ISSUE TITLE
Data refresh range

### ISSUE THREAD

**Issue by peter-power-594** [bkolicoski/arduino-youtube-sight#1]
Good day Blagojce Bill,

Congratulations on the good work! I tried to test your youtube sight API, it's working well. 
Currently, it looks like the data are only updated once per day. 
Is it coming from youtube or did you modify the specifications on your side?

Thank you very much in advance for your help,

Peter

**Comment by bkolicoski** [comment]
Hi Peter, 

Yes, unfortunately, this is a limitation from the Analytics API. There are more details about it here: https://stackoverflow.com/questions/13018142/latency-with-youtube-analytics-api

On my end I do pull data more often in case they decide to provide stats sooner but that really does not happen.
